### PR TITLE
Allergen choices

### LINKED ISSUE #285: Add allergen choices
Continuation of #283. The idea is to add a list of choices in the user profile, for the common allergens and common food preferences.

For the allergens we can use the 14 specified [here (EN)](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32011R1169#d1e32-43-1) and [here (NL)](https://eur-lex.europa.eu/legal-content/NL/TXT/HTML/?uri=CELEX:32011R1169#d1e32-43-1) in Annex II. For the preferences/wishes probably vegetarian, vegan, pescetarian. And a 'other' field for the exceptions.

Any input before I might implement it (if I have time)? @DutcherNL @LenaWil @Ndoll1

### PR DESCRIPTION
**Pull request by mhvis**
Closes #285 

## User notice (disappears after save)

image

## Profile settings

image

## Dining list info

image

## Dining list allergies tab

image

### CODE REVIEW

**Comment by mhvis** [comment]
I wrote this quickly but I think it's reasonably complete now.

Texts can probably be improved. Probably other things too.

**Review by Ndoll1 — COMMENTED** [review]
Have you taken in consideration that other preferences can be present (example no beans). I believe you did, but better check it before you make this active.

**Review by LenaWil — APPROVED** [review]
Nicky says it’s okay!
😜

**Comment by LenaWil** [comment]
Also it seems to work.

**Comment by mhvis** [comment]
Haha thanks! I will merge these 2 PRs and lets see if the site explodes.

**Pull request merged**
